name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          bionic,
          xenial,
          focal,
          ubuntu-latest
        ]

        include:
          - name: bionic
            os: ubuntu-18.04
            artifact_name: target/release/sawtooth-prune-db
            asset_name: sawtooth-prune-db-ubuntu-bionic
          - name: xenial
            os: ubuntu-16.04
            artifact_name: target/release/sawtooth-prune-db
            asset_name: sawtooth-prune-db-ubuntu-xenial
          - name: focal
            os: ubuntu-20.04
            artifact_name: target/release/sawtooth-prune-db
            asset_name: sawtooth-prune-db-ubuntu-focal
          - name: ubuntu-latest
            os: ubuntu-latest
            artifact_name: target/release/sawtooth-prune-db
            asset_name: sawtooth-prune-db-ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        
    - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make gcc protobuf-compiler pkg-config

    - name: Build
      run: cargo build --release --locked

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}